services:
  - type: web
    name: app-laravel
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://tu-app.onrender.com
      - key: APP_KEY
        value: base64:tu_app_key
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: tu_host_db
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: tu_bd
      - key: DB_USERNAME
        value: tu_usuario
      - key: DB_PASSWORD
        value: tu_password
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
